services:
  - type: web
    name: recyclemoi-api
    env: docker
    dockerfilePath: ./backend-api/Dockerfile
    dockerContext: ./backend-api
    region: frankfurt  # Ou oregon/singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
      - key: MODEL_URL
        value: https://huggingface.co/bahani/recyclemoi-resnet18/blob/main/best_model.pth
